"""Strict, local-only sparse asset selection for the JY grammar renderer.

This module is deliberately a small gate in front of the legacy visual
binding code.  It never searches, downloads, calls an image provider, or
turns a generic keyword intersection into a visual event.  A-roll remains the
truthful fallback whenever a concrete object/process is not evidenced by the
current transcript and an already cached, authorized asset.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from typing import Any

from src.services.local_visual_asset_matcher import (
    is_generic_fallback,
    match_local_visual_asset,
    query_visual_concepts,
)

SPARSE_ASSET_MODE = "SPARSE_ASSET_V1"
SPARSE_ASSET_ALLOWED_ROLES = frozenset(
    {
        "PRODUCT",
        "PROCESS",
        "STEP",
        "SCENE",
        "LOCATION",
        "EXAMPLE",
        "SPECIFIC_OBJECT",
        "BEFORE_AFTER",
    }
)
SPARSE_ASSET_ALLOWED_ORIGINS = frozenset(
    {
        "user_owned",
        "approved_local_asset",
        "local_uploaded_asset",
        # Existing generated bytes may be used for a local preview only when
        # the caller explicitly opts in.  They never become publish-cleared
        # assets merely by passing this planning gate.
        "generated_image_asset",
        # Existing provider-cache bytes are already local and rights-confirmed.
        # This is an allowlist entry, not permission to search that provider.
        "stock_video_asset",
    }
)
SPARSE_ASSET_ALLOWED_SOURCE_TYPES = frozenset(
    {
        "manual_upload",
        "local_upload",
        "provider_cache",
        "approved_local_asset",
        "built_in_image_generation",
    }
)
SPARSE_ASSET_MAX_PIP = 5
SPARSE_ASSET_MAX_FULL = 1
SPARSE_ASSET_MIN_GAP_SECONDS = 8.0
SPARSE_ASSET_MIN_DURATION_SECONDS = 1.5
_EXTERNAL_STOCK_PROVIDERS = frozenset({"pexels", "pixabay"})

# These are category signals, not sample copy.  They are intentionally small:
# a segment must contain a concrete object/place/action signal before a broad
# matcher concept can open the asset gate.
_CONCRETE_ROLE_SIGNALS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "restaurant",
        (
            "餐饮",
            "餐厅",
            "烧烤",
            "烤肉",
            "门店",
            "店里",
            "招牌",
            "菜",
            "食物",
            "restaurant",
            "barbecue",
            "grill",
            "dining",
            "food",
        ),
    ),
    (
        "loyalty",
        (
            "会员",
            "充值",
            "优惠券",
            "扫码",
            "二维码",
            "领取",
            "转介绍",
            "customer signup",
            "membership",
            "coupon",
            "qr code",
            "referral",
        ),
    ),
    (
        "workflow",
        (
            "流程",
            "步骤",
            "操作",
            "设置",
            "教程",
            "执行",
            "process",
            "workflow",
            "tutorial",
        ),
    ),
    (
        "data_system",
        (
            "数据库",
            "客户名单",
            "客户资源",
            "库存",
            "crm",
            "dashboard",
            "data",
            "database",
            "customer list",
            "inventory",
        ),
    ),
    (
        "multi_industry",
        (
            "水果",
            "生鲜",
            "美容",
            "便利店",
            "零售",
            "beauty",
            "fresh",
            "convenience",
            "retail",
        ),
    ),
)
_ACTION_SIGNALS = (
    "办",
    "送",
    "发",
    "领",
    "扫",
    "充",
    "设",
    "做",
    "执行",
    "操作",
    "安装",
    "领取",
    "signup",
    "scan",
    "install",
    "process",
)

# A category word such as ``顾客`` or ``店里`` is not enough to justify a
# food/restaurant cutaway.  These are deliberately concrete, visible cues:
# they describe the object or action that should actually be present in the
# cached footage.  The list is a semantic gate, not a sample-video lookup.
_STRONG_RESTAURANT_SIGNALS = (
    "餐饮",
    "餐厅",
    "烧烤",
    "烤肉",
    "招牌",
    "菜",
    "食物",
    "食材",
    "厨房",
    "烹饪",
    "烤",
    "restaurant",
    "barbecue",
    "bbq",
    "grill",
    "dining",
    "food",
    "meal",
    "ribs",
)
_FOOD_OBJECT_ACTION_SIGNALS = (
    "招牌",
    "菜",
    "食物",
    "食材",
    "厨房",
    "烹饪",
    "烧烤",
    "烤肉",
    "烧",
    "烤",
    "meal",
    "food",
    "grill",
    "bbq",
    "barbecue",
    "ribs",
    "cooking",
    "preparation",
    "hamburger",
)
_INDUSTRY_SIGNALS: dict[str, tuple[str, ...]] = {
    "convenience": ("便利店", "convenience"),
    "beauty": ("美容", "美业", "beauty", "salon"),
    "fresh_food": ("水果", "生鲜", "fresh", "produce"),
    "restaurant": _STRONG_RESTAURANT_SIGNALS,
}


def _compact(value: object) -> str:
    return re.sub(r"\s+", "", str(value or "")).casefold()


def _text(segment: Mapping[str, Any]) -> str:
    return re.sub(r"\s+", "", str(segment.get("text") or "")).strip()


def _concrete_concepts(text: str) -> set[str]:
    compact = _compact(text)
    return {
        concept
        for concept, signals in _CONCRETE_ROLE_SIGNALS
        if any(_compact(signal) in compact for signal in signals)
    }


def _asset_evidence_text(asset: Mapping[str, Any]) -> str:
    """Return only visible/curated asset evidence, never the search intent."""

    values: list[str] = []
    for key in (
        "name",
        "original_name",
        "title",
        "description",
        "provider_title",
        "provider_description",
        "provider_tags",
        "semantic_binding",
        "visual_keywords",
        "source_url",
    ):
        value = asset.get(key)
        if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
            values.extend(_compact(item) for item in value if _compact(item))
        elif _compact(value):
            values.append(_compact(value))
    # ``semantic_query``/``keywords`` explain why a provider search was made;
    # they are not visual proof for a cached provider result.
    if _compact(asset.get("source_type")) != "provider_cache":
        keywords = asset.get("keywords")
        if isinstance(keywords, Sequence) and not isinstance(keywords, (str, bytes)):
            values.extend(_compact(item) for item in keywords if _compact(item))
    return " ".join(dict.fromkeys(values))


def _strict_asset_compatibility(
    text: str,
    asset: Mapping[str, Any],
) -> tuple[bool, str]:
    """Reject category-only matches that do not answer the spoken sentence.

    The generic matcher is intentionally recall-oriented.  Sparse assets need
    a stricter second gate: the source must name a concrete visual subject and
    the asset's visible metadata must contain the same subject/industry cue.
    """

    query = _compact(text)
    evidence = _asset_evidence_text(asset)
    strong_restaurant_query = any(_compact(term) in query for term in _STRONG_RESTAURANT_SIGNALS)
    if strong_restaurant_query and not any(
        _compact(term) in evidence for term in _STRONG_RESTAURANT_SIGNALS
    ):
        return False, "asset_missing_spoken_restaurant_subject"
    food_specific_query = any(
        _compact(term) in query for term in _FOOD_OBJECT_ACTION_SIGNALS
    )
    food_specific_evidence = any(
        _compact(term) in evidence for term in _FOOD_OBJECT_ACTION_SIGNALS
    )
    if food_specific_query and not food_specific_evidence:
        return False, "asset_missing_spoken_food_object_or_action"

    # A single named industry is a concrete example, not a generic
    # multi-industry category.  Do not let a beauty clip satisfy a convenience
    # store sentence merely because both are classified as ``multi_industry``.
    named_industries = [
        (name, terms)
        for name, terms in _INDUSTRY_SIGNALS.items()
        if any(_compact(term) in query for term in terms)
    ]
    if len(named_industries) > 1:
        return False, "multi_industry_sentence_needs_a_specific_single_subject"
    if named_industries:
        matching_industry = any(
            any(_compact(term) in evidence for term in terms)
            for _name, terms in named_industries
        )
        if not matching_industry:
            return False, "asset_industry_does_not_match_spoken_example"

    # ``顾客``/``店里``/``门店`` alone open no visual gate.  However, do not
    # reject a sentence merely because it also contains one of those broad
    # words: a customer-owned clip can still be a precise match for a concrete
    # object/action in the same sentence (for example a verified app demo).
    # The concept intersection is derived from the current sentence and asset
    # metadata; it is not a topic-specific allowlist.
    generic_business_terms = ("顾客", "店里", "门店", "回头客")
    if any(term in query for term in generic_business_terms) and not strong_restaurant_query:
        query_without_generic_business_terms = query
        for generic_term in generic_business_terms:
            query_without_generic_business_terms = query_without_generic_business_terms.replace(
                generic_term, ""
            )
        query_specific_concepts = query_visual_concepts(
            query_without_generic_business_terms
        )
        evidence_specific_concepts = query_visual_concepts(evidence)
        if not query_specific_concepts.intersection(evidence_specific_concepts):
            return False, "spoken_text_has_only_generic_business_scene"
    return True, "specific_subject_and_visible_asset_evidence_match"


def _roles_for_segment(text: str, annotation: Mapping[str, Any] | None) -> list[str]:
    current = [
        str(role)
        for role in (annotation or {}).get("semantic_roles") or []
        if str(role) in SPARSE_ASSET_ALLOWED_ROLES
    ]
    concepts = _concrete_concepts(text)
    roles: list[str] = []
    if "restaurant" in concepts:
        # A place/food signal is scene evidence; an action around that signal
        # is a process.  Do not let a pure benefit/number sentence open assets.
        roles.append("PROCESS" if any(signal in text for signal in _ACTION_SIGNALS) else "SCENE")
        if any(signal in text for signal in ("菜", "食物", "招牌", "产品", "food", "meal")):
            roles.insert(0, "PRODUCT")
    if "loyalty" in concepts and any(signal in text for signal in _ACTION_SIGNALS):
        roles.append("PROCESS")
    if "workflow" in concepts:
        roles.append("STEP" if any(signal in text for signal in ("步骤", "第一", "第二", "首先", "其次")) else "PROCESS")
    if "data_system" in concepts:
        # A database, inventory, CRM or customer list is a concrete visual
        # subject even when the transcript classifier did not assign a strong
        # role.  Keep it in the process/product lane; abstract benefits still
        # do not open the gate without a concrete concept.
        roles.append("PROCESS" if any(signal in text for signal in ("沉淀", "管理", "使用", "掌握", "变成", "库存")) else "PRODUCT")
    if "multi_industry" in concepts:
        roles.append("EXAMPLE")
    roles.extend(current)
    return list(dict.fromkeys(role for role in roles if role in SPARSE_ASSET_ALLOWED_ROLES))


def _asset_is_allowed(
    asset: Mapping[str, Any], *, allow_generated_preview: bool = False
) -> bool:
    origin = _compact(asset.get("asset_origin"))
    source_type = _compact(asset.get("source_type"))
    authorization = _compact(asset.get("authorization_status"))
    if origin not in SPARSE_ASSET_ALLOWED_ORIGINS:
        return False
    if source_type not in SPARSE_ASSET_ALLOWED_SOURCE_TYPES:
        return False
    if origin == "generated_image_asset":
        if not allow_generated_preview:
            return False
        if authorization != "generated_for_local_acceptance":
            return False
        if _compact(asset.get("rights_status")) != "generated_for_local_acceptance":
            return False
        if bool(asset.get("cloud_upload")) or bool(asset.get("paid_stock_call")):
            return False
    elif authorization != "confirmed":
        return False
    # A rights-confirmed external clip is not automatically a truthful visual
    # for a Chinese/local case.  Sparse assets must fail closed here: only an
    # explicitly domestic external cache item may pass this gate.  User-owned
    # and approved local assets keep their existing behavior even when they do
    # not carry a domestic_context field.
    if origin == "stock_video_asset":
        provider = _compact(asset.get("source_provider"))
        domestic_context = _compact(asset.get("domestic_context"))
        if provider in _EXTERNAL_STOCK_PROVIDERS or domestic_context != "domestic":
            return False
    if is_generic_fallback(asset):
        return False
    return bool(str(asset.get("asset_id") or "").strip())


def _score_summary(
    *,
    match: Mapping[str, Any],
    text: str,
    mode: str,
) -> dict[str, float]:
    score = float(match.get("match_score") or 0)
    semantic_match = max(0.0, min(1.0, score / 80.0))
    specific_signal = bool(_concrete_concepts(text))
    specificity = 0.9 if specific_signal else 0.0
    # Side-float PiP is deliberately smaller and safer than a full-screen
    # cutaway.  Full-screen is only ever selected by an explicit caller.
    obstruction_risk = 0.18 if mode == "pip" else 0.34
    visual_value = max(
        0.0,
        min(1.0, semantic_match * 0.55 + specificity * 0.35 + (1 - obstruction_risk) * 0.10),
    )
    return {
        "semantic_match": round(semantic_match, 3),
        "specificity": round(specificity, 3),
        "visual_value": round(visual_value, 3),
        "obstruction_risk": round(obstruction_risk, 3),
    }


def build_sparse_asset_plan(
    segments: Sequence[Mapping[str, Any]],
    local_assets: Sequence[Mapping[str, Any]],
    *,
    duration_seconds: float = 0.0,
    max_pip: int = SPARSE_ASSET_MAX_PIP,
    max_full: int = SPARSE_ASSET_MAX_FULL,
    allow_generated_preview: bool = False,
) -> dict[str, Any]:
    """Select a few high-value local assets, with an auditable rejection log."""

    annotations_by_index: dict[int, Mapping[str, Any]] = {}
    try:
        from src.services.grammar_only import annotate_transcript_segments

        annotations_by_index = {
            int(item.get("source_segment_index")): item
            for item in annotate_transcript_segments(
                segments, duration_seconds=duration_seconds
            )
            if isinstance(item, Mapping) and item.get("source_segment_index") is not None
        }
    except Exception:
        annotations_by_index = {}

    eligible_assets = [
        asset
        for asset in local_assets
        if isinstance(asset, Mapping)
        and _asset_is_allowed(
            asset,
            allow_generated_preview=allow_generated_preview,
        )
    ]
    plan: dict[str, Any] = {
        "mode": SPARSE_ASSET_MODE,
        "asset_events": [],
        "rejections": [],
        "source_policy": {
            "allowed": ["user_owned", "approved_local_asset", "minimax_generated", "confirmed_local_cache"],
            "provider_search_calls": 0,
            "network_downloads": 0,
            "minimax_image_calls": 0,
            "fallback": "a_roll",
            "generated_preview_enabled": bool(allow_generated_preview),
        },
    }
    used_asset_ids: list[str] = []
    accepted_starts: list[float] = []
    ordered_segments = sorted(
        (segment for segment in segments if isinstance(segment, Mapping)),
        key=lambda segment: float(segment.get("start") or 0),
    )
    target_pip = max(0, min(int(max_pip), SPARSE_ASSET_MAX_PIP))
    target_full = max(0, min(int(max_full), SPARSE_ASSET_MAX_FULL))
    for index, segment in enumerate(ordered_segments):
        text = _text(segment)
        if not text:
            continue
        start = float(segment.get("start") or 0)
        end = float(segment.get("end") or start)
        if end - start < SPARSE_ASSET_MIN_DURATION_SECONDS:
            continue
        annotation = annotations_by_index.get(int(segment.get("source_segment_index", index)))
        roles = _roles_for_segment(text, annotation)
        if not roles:
            continue
        if any(abs(start - previous) < SPARSE_ASSET_MIN_GAP_SECONDS for previous in accepted_starts):
            plan["rejections"].append({"segment_index": index, "semantic_text": text[:48], "reason": "asset_spacing_guard"})
            continue
        query_concepts = query_visual_concepts(text)
        if not query_concepts:
            plan["rejections"].append({"segment_index": index, "semantic_text": text[:48], "reason": "no_concrete_visual_concept"})
            continue
        compact_text = _compact(text)
        has_strong_restaurant = any(
            _compact(signal) in compact_text
            for signal in _STRONG_RESTAURANT_SIGNALS
        )
        named_industry_count = sum(
            1
            for _name, signals in _INDUSTRY_SIGNALS.items()
            if any(_compact(signal) in compact_text for signal in signals)
        )
        if named_industry_count > 1:
            plan["rejections"].append(
                {
                    "segment_index": index,
                    "semantic_text": text[:48],
                    "reason": "asset_specificity_gate",
                    "detail": "multi_industry_sentence_needs_a_specific_single_subject",
                }
            )
            continue
        query_without_generic_business_terms = compact_text
        for generic_term in ("顾客", "店里", "门店", "回头客"):
            query_without_generic_business_terms = query_without_generic_business_terms.replace(
                generic_term, ""
            )
        compatible_assets = [
            asset
            for asset in eligible_assets
            if _strict_asset_compatibility(text, asset)[0]
        ]
        if not compatible_assets:
            generic_business_only = (
                any(term in compact_text for term in ("顾客", "店里", "门店", "回头客"))
                and not has_strong_restaurant
                and query_visual_concepts(query_without_generic_business_terms)
                <= {"loyalty"}
            )
            plan["rejections"].append(
                {
                    "segment_index": index,
                    "semantic_text": text[:48],
                    "reason": (
                        "asset_specificity_gate"
                        if eligible_assets
                        else "no_authorized_specific_local_match"
                    ),
                    "detail": (
                        "spoken_text_has_only_generic_business_scene"
                        if generic_business_only
                        else (
                            "no_visible_asset_evidence_matches_concrete_subject"
                            if eligible_assets
                            else "no_authorized_asset_in_allowlist"
                        )
                    ),
                }
            )
            continue
        match = match_local_visual_asset(
            text,
            compatible_assets,
            used_asset_ids=used_asset_ids,
            allow_generic_fallback=False,
        )
        if match is None:
            plan["rejections"].append({"segment_index": index, "semantic_text": text[:48], "reason": "no_authorized_specific_local_match"})
            continue
        mode = "full" if not plan["asset_events"] and target_full > 0 else "pip"
        if mode == "full" and sum(event.get("mode") == "full" for event in plan["asset_events"]) >= target_full:
            mode = "pip"
        if mode == "pip" and sum(event.get("mode") == "pip" for event in plan["asset_events"]) >= target_pip:
            break
        score = _score_summary(match=match, text=text, mode=mode)
        reasons = [str(reason) for reason in match.get("match_reason") or []]
        compatible, compatibility_reason = _strict_asset_compatibility(text, match)
        if not compatible:
            plan["rejections"].append(
                {
                    "segment_index": index,
                    "semantic_text": text[:48],
                    "reason": "asset_specificity_gate",
                    "detail": compatibility_reason,
                    "scores": score,
                    "match_reason": reasons,
                }
            )
            continue
        if (
            score["semantic_match"] < 0.65
            or score["specificity"] < 0.75
            or score["visual_value"] < 0.65
            or not any("concrete_visual_" in reason for reason in reasons)
        ):
            plan["rejections"].append(
                {
                    "segment_index": index,
                    "semantic_text": text[:48],
                    "reason": "asset_value_gate",
                    "scores": score,
                    "match_reason": reasons,
                }
            )
            continue
        asset_id = str(match.get("asset_id") or "")
        used_asset_ids.append(asset_id)
        accepted_starts.append(start)
        plan["asset_events"].append(
            {
                "event_id": f"sparse-asset-{len(plan['asset_events']) + 1:02d}",
                "asset_id": asset_id,
                "start": round(start, 3),
                "end": round(min(end, start + (2.4 if mode == "pip" else 3.2)), 3),
                "mode": mode,
                "layout": "PIP_SIDE_FLOAT" if mode == "pip" else "FULL_SCREEN",
                "semantic_role": roles[0],
                "semantic_roles": roles,
                "semantic_text": text[:48],
                "source_text": text,
                "selection_reason": "具体语义角色与本地素材概念交集通过 Asset Value Gate；其余位置保留 A-roll。",
                "compatibility_reason": compatibility_reason,
                "match_score": match.get("match_score"),
                "match_reason": reasons,
                "asset_origin": match.get("asset_origin"),
                "source_type": match.get("source_type"),
                "source_provider": match.get("source_provider"),
                "authorization_status": match.get("authorization_status"),
                "publish_licensed": bool(match.get("publish_licensed", False)),
                "preview_only": str(match.get("asset_origin") or "")
                == "generated_image_asset",
                **score,
            }
        )
    plan["pip_count"] = sum(event.get("mode") == "pip" for event in plan["asset_events"])
    plan["full_screen_count"] = sum(event.get("mode") == "full" for event in plan["asset_events"])
    plan["asset_count"] = len(plan["asset_events"])
    return plan


def validate_sparse_asset_plan(plan: Mapping[str, Any]) -> list[str]:
    """Fail closed if a sparse plan contains an old/unsafe visual path."""

    violations: list[str] = []
    if str(plan.get("mode") or "") != SPARSE_ASSET_MODE:
        violations.append("mode_not_sparse_asset_v1")
    events = plan.get("asset_events") or []
    if not isinstance(events, Sequence) or isinstance(events, (str, bytes)):
        return [*violations, "asset_events_not_list"]
    pip_count = 0
    full_count = 0
    previous: list[float] = []
    for index, event in enumerate(events):
        if not isinstance(event, Mapping):
            violations.append(f"asset_events[{index}]_not_object")
            continue
        path = f"asset_events[{index}]"
        role = str(event.get("semantic_role") or "")
        if role not in SPARSE_ASSET_ALLOWED_ROLES:
            violations.append(f"{path}.semantic_role_not_allowed")
        source_text = str(event.get("source_text") or "")
        semantic_text = str(event.get("semantic_text") or "")
        if not semantic_text or semantic_text not in source_text:
            violations.append(f"{path}.semantic_text_not_grounded")
        try:
            start = float(event.get("start") or 0)
            end = float(event.get("end") or 0)
        except (TypeError, ValueError):
            violations.append(f"{path}.invalid_time")
            continue
        if end <= start or end - start > 3.6:
            violations.append(f"{path}.invalid_duration")
        if any(abs(start - prior) < 8.0 for prior in previous):
            violations.append(f"{path}.spacing_violation")
        previous.append(start)
        mode = str(event.get("mode") or "")
        if mode == "pip":
            pip_count += 1
            if str(event.get("layout") or "") != "PIP_SIDE_FLOAT":
                violations.append(f"{path}.pip_layout_not_allowed")
        elif mode == "full":
            full_count += 1
            if str(event.get("layout") or "") != "FULL_SCREEN":
                violations.append(f"{path}.full_layout_not_allowed")
        else:
            violations.append(f"{path}.mode_not_allowed")
        if str(event.get("asset_origin") or "") not in SPARSE_ASSET_ALLOWED_ORIGINS:
            violations.append(f"{path}.asset_origin_not_allowed")
        if str(event.get("source_type") or "") not in SPARSE_ASSET_ALLOWED_SOURCE_TYPES:
            violations.append(f"{path}.source_type_not_allowed")
        authorization = str(event.get("authorization_status") or "")
        is_generated_preview = (
            str(event.get("asset_origin") or "") == "generated_image_asset"
        )
        if authorization != "confirmed" and not (
            is_generated_preview and authorization == "generated_for_local_acceptance"
        ):
            violations.append(f"{path}.authorization_not_confirmed")
        if is_generated_preview and not bool(event.get("preview_only")):
            violations.append(f"{path}.generated_preview_not_marked")
        for score_key in ("semantic_match", "specificity", "visual_value", "obstruction_risk"):
            if not isinstance(event.get(score_key), (int, float)):
                violations.append(f"{path}.{score_key}_missing")
    if pip_count > SPARSE_ASSET_MAX_PIP:
        violations.append("pip_budget_exceeded")
    if full_count > SPARSE_ASSET_MAX_FULL:
        violations.append("full_screen_budget_exceeded")
    return sorted(set(violations))
